build: off

init:
  - git config --global core.autocrlf input

install:
  - java -version
  - SET JAVA_HOME=C:\jdk8
  - SET PATH=C:\jdk8\bin;%PATH%
  - cmd: choco install sbt --version 0.13.15 -ia "INSTALLDIR=""C:\sbt""" -y -v -d
  - cmd: choco upgrade sbt -y
  - cmd: SET PATH=C:\sbt\bin;%JAVA_HOME%\bin;%PATH%
  - cmd: SET SBT_OPTS=-XX:MaxPermSize=2g -Xmx4g
  - cmd: SET JAVA_OPTS=-XX:MaxPermSize=2g -Xmx4g
  - ps: Install-Product node $env:nodejs_version
  - node --version
  - npm --version
  - npm install

cache:
  - C:\Users\appveyor\.sbt
  - C:\Users\appveyor\.m2
  - C:\Users\appveyor\.ivy2
  - node_modules -> package.json


branches:
  only:
    - master
shallow_clone: true
clone_depth: 1

environment:
  matrix:
    - nodejs_version: "10"
    - nodejs_version: "8"
    - nodejs_version: "6"

test_script:
  - npm test
  - npm run test-system

