build: off
os: Windows Server 2012

init:
  - git config --global core.autocrlf input

install:
  - cmd: choco install zulu8 -ia "INSTALLDIR=""C:\zulu"""
  - cmd: SET JAVA_HOME="C:\zulu"
  - cmd: choco install sbt -ia "INSTALLDIR=""C:\sbt"""
  - cmd: SET PATH=C:\sbt\bin;%JAVA_HOME%\bin;%PATH%
  - cmd: SET SBT_OPTS=-Xms4g -Xmx4g
  - cmd: SET COURSIER_VERBOSITY=-1
  - cmd: SET JAVA_OPTS=-Xms4g -Xmx4g
  - ps: Install-Product node $env:nodejs_version
  - java -version
  - node --version
  - npm --version
  - npm install

cache:
  - '%USERPROFILE%\.ivy2'
  - '%USERPROFILE%\.sbt'
  - node_modules -> package.json
  - C:\Users\appveyor\.m2


branches:
  only:
    - master
shallow_clone: true
clone_depth: 1

environment:
  matrix:
    - nodejs_version: "10"
    - nodejs_version: "8"
    - nodejs_version: "6"

test_script:
  - npm test
  - npm run test-system-windows
